export const PRODUCTS_ACTION_TYPES = {
    FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
    FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_FAILED: "FETCH_PRODUCTS_FAILED",
    SET_CURRENT_CATEGORY: "SET_CURRENT_CATEGORY",
    SET_SEARCH_STRING: "SET_SEARCH_STRING"
}